name: Lint

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo fmt --check --all
    - name: Clippy
      run: cargo clippy

DO NOT MERGE
